
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Oz Motorz
subtitle: "Electric Bicycles"
url: "http://mike-osborn.github.io" # the base hostname & protocol for your site
baseurl: "/ozmotorz-jekyll"
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
